import pandas as pd
df = pd.read_csv('titanic.csv')
print(df.head())
print("shape:",df.shape)
print(df.info())
print(df.describe())
survival=df.groupby("Survived")["PassengerId"].count()
print("\nSurvival count:")
print (survival)
fare_by_class = df.groupby("Pclass")["Fare"].mean().round(2)
print("\nAverage fare by class:")
print(fare_by_class)
# Survival rate by gender
survival_gender = df.groupby("Sex")["Survived"].mean().round(2)
print("\nSurvival rate by gender:")
print(survival_gender)
